### PR TITLE
Suggestion: Ansible

### PR DESCRIPTION
**Pull request by tvogels**
I used this to setup a few nodes for myself. I would trying this for all our group nodes:

Advantages:
- If we want to add a package on all our servers, we can just add it to these config files and rerun them. Ansible will do the minimum update to make the state of the servers consistent with the specification.

### CODE REVIEW

**Comment by jbcdnr** [comment]
Looks very nice! We just need the `gpu-monitor` interface and it would be a drop in replacement for the current (buggy) deployment script :) Great configuration!

**Comment by tvogels** [comment]
Yeah, GPU monitor and mlo-container-scratch.

There is something tricky with setting up the mount of mlo-container-scratch. Whenever I add it and reboot afterwards, I cannot login anymore.

**Comment by jbcdnr** [comment]
But there is no problem with `/mlodata1` ?

**Comment by tvogels** [comment]
No, that one works fine. They are also not quite the same. mlodata1 is NFS, and I think mlo-container-scratch is CEPH or so.

**Comment by tvogels** [comment]
I think this is ready to be merged and used. Shall we?

**Comment by jbcdnr** [comment]
Yes :)
Are we only missing the GPU monitor scripts ?

**Comment by tvogels** [comment]
I thought they were in there already?

**Comment by jbcdnr** [comment]
No, I have moved the web interface. @theevann wanted to clean the scripts with Cron so I did not add the current scripts. 

Do you have a running supervisor.d service already set up?

**Comment by tvogels** [comment]
> Do you have a running supervisor.d service already set up?

I think you added this in 2590cef, but we reverted this in 27defec because the commit wasn't complete and led to errors.

**Comment by tvogels** [comment]
I think we solved all of the remaining issues.
Should we merge this?

**Comment by jbcdnr** [comment]
Looks good to me! :)

**Pull request merged**
